version: '2'
services:
  web:
    image: tiangolo/uwsgi-nginx-flask:python3.6
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
  sqlite:
    image: nouchka/sqlite3
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
